server:
  port: 8080

spring:
  application:
    name: organization-panel-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bnpl_db}
    username: ${DB_USER:bnpl}
    password: ${DB_PASSWORD:bnpl@nilva}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/realms/bnpl}

management:
  endpoints:
    web:
      exposure:
        include: health,info,db
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: true

logging:
  level:
    root: INFO
    com.organizational.bnpl.panel: DEBUG
    liquibase: INFO
